title: sinji blog
description: > # this means to ignore newlines until "baseurl:"
  ì €ë¥¼ ì†Œê°œí•˜ëŠ” ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinji2102.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Sinji Yun
tagline: FrontEnd Developer
about-description: ë¬¸ì œë¥¼ í•´ê²°í•  ë•Œ ê¸°ì¨ì„ ëŠë¼ëŠ” ì›¹ ê°œë°œì ìœ¤ì‹ ì§€ì…ë‹ˆë‹¤. ì–´ì©Œê³  ì €ì©Œê³  ìê¸°ì†Œê°œ ì‘ì„±í•´ ì£¼ì‹œë©´ ë©ë‹ˆë‹¤! ìš©ë¬¸ê³  í•™ìƒë“¤ íŒŒì´íŒ…í•˜ì„¸ìš” ğŸ”¥
pic: 79.jpg  

# Contact links
email: sinji.3010@gmail.com # Add your Email address
phone: 010-2247-9474 # Add your Phone number
website: velog.io/@dawnww/posts # Add your website, do not add http://
github: sinji2102 # Add your Github handle
instagram: 'd_awnww'

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
